# Common Configuration
leetcode:
  api:
    base-url: https://leetcode.com/graphql
    content-type: application/json
    username: edwinhern
  client:
    connect-timeout: 5000
    read-timeout: 5000
    retry:
      max-attempts: 3
      delay: 1000
  sync:
    cron: 0 */1 * * * *

spring:
  application:
    name: activity-tracker
  profiles:
    active: local
  flyway:
    locations: classpath:migrations
    enabled: true
    baseline-on-migrate: true
  jpa:
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        connection:
          provider_disables_autocommit: false

server:
  port: 8080

logging:
  level:
    org.springframework.web: INFO
    com.activity: DEBUG
    com.zaxxer.hikari.HikariConfig: DEBUG
    com.zaxxer.hikari: TRACE

springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true

plaid:
  client-id: ${PLAID_CLIENT_ID}
  secret: ${PLAID_SECRET}
  env: sandbox

---
# Local Development Profile
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:postgresql://localhost:5432/activity_tracker
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: ActivityTrackerPool
      minimum-idle: 5
      maximum-pool-size: 10
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-timeout: 20000
      auto-commit: true
      connection-test-query: SELECT 1
      validation-timeout: 5000
  jpa:
    hibernate:
      ddl-auto: validate
  redis:
    host: localhost
    port: 6379
  # kafka:
  #   bootstrap-servers: localhost:9092
  #   consumer:
  #     group-id: activity-tracker-group
  #     auto-offset-reset: earliest
  #     key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  #     value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  #   producer:
  #     key-serializer: org.apache.kafka.common.serialization.StringSerializer
  #     value-serializer: org.apache.kafka.common.serialization.StringSerializer

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

---
# Docker Profile
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:postgresql://postgres:5432/activity_tracker
    username: postgres
    password: postgres
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: ActivityTrackerPool
      minimum-idle: 5
      maximum-pool-size: 10
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-timeout: 20000
      auto-commit: true
      connection-test-query: SELECT 1
      validation-timeout: 5000
  redis:
    host: redis
  # kafka:
  #   bootstrap-servers: kafka:29092
